version: "3.8"
services:
  postgres:
    image: postgres
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      POSTGRES_PASSWORD: rubeusintegration
      POSTGRES_DB: rubeusintegration

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 15s
      retries: 5

    ports:
      - 5432:5432

    networks:
      - rubeusintegration-network

  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - ../:/app
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: rubeusintegration
      POSTGRES_DATABASE: rubeusintegration

    ports:
      - 3333:3333

    networks:
      - rubeusintegration-network

    depends_on:
      postgres:
        condition: service_healthy

networks:
  rubeusintegration-network:
    driver: "bridge"
